language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "jevering"
    token:
      secure: "f6536af917cae8b4caf9879c8df6b9013b290f04" # encrypted value of your token
script:
  - ant build
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
